create table if not exists public.chamados (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  contato text not null,
  loja text not null,
  setor text not null,
  categoria text not null,
  prioridade text not null,
  titulo text not null,
  descricao text not null,
  status text not null default 'Aberto',
  origem text not null default 'site'
);

alter table public.chamados enable row level security;

create policy "Permitir abertura publica de chamados"
on public.chamados
for insert
to anon
with check (true);

create policy "Bloquear leitura publica dos chamados"
on public.chamados
for select
to anon
using (false);
