create table if not exists public.chamados (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  contato text not null,
  loja text not null,
  setor text not null,
  categoria text not null,
 
  titulo text not null,
  descricao text not null,
  status text not null default 'Aberto',
  origem text not null default 'site'
);

alter table public.chamados
  add column if not exists contato text,
  add column if not exists loja text,
  add column if not exists setor text,
  add column if not exists categoria text,
  add column if not exists titulo text,
  add column if not exists descricao text,
  add column if not exists status text default 'Aberto',
  add column if not exists origem text default 'site';

alter table public.chamados enable row level security;

create policy "Permitir abertura publica de chamados"
on public.chamados
for insert
to anon
with check (true);

create policy "Bloquear leitura publica dos chamados"
on public.chamados
for select
to anon
using (false);

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'chamados'
      and policyname = 'Permitir leitura para usuarios autenticados'
  ) then
    create policy "Permitir leitura para usuarios autenticados"
    on public.chamados
    for select
    to authenticated
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'chamados'
      and policyname = 'Permitir atualizar status para usuarios autenticados'
  ) then
    create policy "Permitir atualizar status para usuarios autenticados"
    on public.chamados
    for update
    to authenticated
    using (true)
    with check (true);
  end if;
end
$$;
