create table if not exists public.chamados (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.chamados
  add column if not exists nome text,
  add column if not exists contato text,
  add column if not exists loja text,
  add column if not exists setor text,
  add column if not exists categoria text,
  add column if not exists prioridade text,
  add column if not exists titulo text,
  add column if not exists descricao text,
  add column if not exists status text default 'Aberto',
  add column if not exists origem text default 'site';

update public.chamados
set
  nome = coalesce(nome, 'Nao informado'),
  contato = coalesce(contato, 'Nao informado'),
  loja = coalesce(loja, 'Nao informado'),
  setor = coalesce(setor, 'Nao informado'),
  categoria = coalesce(categoria, 'Outro'),
  prioridade = coalesce(prioridade, 'Baixa'),
  titulo = coalesce(titulo, 'Chamado sem titulo'),
  descricao = coalesce(descricao, 'Sem descricao'),
  status = coalesce(status, 'Aberto'),
  origem = coalesce(origem, 'site');

alter table public.chamados
  alter column nome set not null,
  alter column contato set not null,
  alter column loja set not null,
  alter column setor set not null,
  alter column categoria set not null,
  alter column prioridade set not null,
  alter column titulo set not null,
  alter column descricao set not null,
  alter column status set not null,
  alter column origem set not null;

alter table public.chamados enable row level security;

drop policy if exists "Permitir abertura publica de chamados" on public.chamados;
drop policy if exists "Bloquear leitura publica dos chamados" on public.chamados;
drop policy if exists "Permitir leitura para usuarios autenticados" on public.chamados;
drop policy if exists "Permitir atualizar status para usuarios autenticados" on public.chamados;

create policy "Permitir abertura publica de chamados"
on public.chamados
for insert
to anon
with check (true);

create policy "Bloquear leitura publica dos chamados"
on public.chamados
for select
to anon
using (false);

create policy "Permitir leitura para usuarios autenticados"
on public.chamados
for select
to authenticated
using (true);

create policy "Permitir atualizar status para usuarios autenticados"
on public.chamados
for update
to authenticated
using (true)
with check (true);
